### ISSUE TITLE
String section与airbnb guide不符 #6.2

### ISSUE THREAD

**Issue by Jiavan** [sivan/javascript-style-guide#4]
Strings that cause the line to go over 100 characters should not be written across multiple lines using string concatenation.

why?Broken strings are painful to work with and make code less searchable.

https://github.com/airbnb/javascript#strings--line-length

**Comment by sivan** [comment]
@Jiavan 感谢反馈。
你指出的位置目前遵循的是 [Airbnb JavaScript ES5](https://github.com/airbnb/javascript/tree/es5-deprecated/es5#strings) 版本的规范。该版本官方现已不再维护，所以未同步进去，为了保持与官方版的一致性我也不修正了 :P

你链接提到 ES6 规范目前正在翻译中，届时字符串相关的描述会同步到最新规范~
